### PR TITLE
Change logo

### PR DESCRIPTION
**Pull request by bates64**
Pros:
* looks like a d (**d**ecent)
* ok :ok_hand: 
  * "decent"
* blue (cc @PullJosh)
* less complex than weird sun-behind-tangerine thing
  * simple is good for logos; should be easily recognisable
  * we don't actually use it yet so this is a good as time as any to iterate

### CODE REVIEW

**Comment by PullJosh** [comment]
Awesome! It's clever, and looks good. :ok_hand:

One question is whether we want to save the file as an inkscape SVG (as opposed to saving it as an "optimized SVG"). Inkscape SVGs will save any special inkscape-specific features you may have used in the image (like a custom grid or alignment lines, among other things), but it makes the file much larger.

If you *didn't* use those features, `File > Save as > Optimized SVG` is the way to go.

**Comment by bates64** [comment]
@PullJosh - Yeah, I totally want to use those fancy optimised SVGs. But automation is fun - any idea on how to use `inkscape`'s CLI to compress/optimise an SVG? See the `Makefile` - we already auto-convert all SVGs to PNGs.

**Comment by PullJosh** [comment]
Under what circumstances would we ever use a PNG version of the logo? Decent targets newer browsers, in which SVG support is exactly 100% (at least for non-jank svg files like ours).

Additionally, all fill and stroke settings can (and should!) be controlled with CSS. We should have two svgs files. One with a single `path` for the hand, and one with the hand path as well as the notification indicator (with an ID so we can color is with CSS as desired).

There's no reason to introduce unneeded complexity.

**Comment by bates64** [comment]
> Decent targets newer browsers

This repo is for anyone who wants to use the Decent logo for whatever reason :ok_man: 
Oh, and also what about the favicon?

> Additionally, all fill and stroke settings can (and should!) be controlled with CSS. We should have two svgs files. One with a single path for the hand, and one with the hand path as well as the notification indicator (with an ID so we can color is with CSS as desired).

Yes, but again that's out-of-scope. I'll replace -black and -white with an unset one though.

**Comment by PullJosh** [comment]
> This repo is for anyone who wants to use the Decent logo for whatever reason :ok_man:

Gotcha. In that case, how about two SVGs, but then generate multiple different colors of PNG from the command line out of the single SVG? Is that a thing that can happen?

**Comment by bates64** [comment]
We can `--export-background` colour but not fill colour as far as I'm aware.

**Pull request merged**
